apiVersion: v1
kind: Pod
metadata: 
   name: result-app-pod
   labels:
      name: result-app-pod
      app: demo-voting-app
spec:
    containers: 
    - name: voting-app
      image: aamz24/result
      ports:
      - containerPort: 80